int _strlen(char *s);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
void _puts(char *str);
int _putchar(char c);
void print_rev(char *s);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
char *_strncpy(char *dest, char *src, int n);
char *cap_string(char *);
char *leet(char *);
char *_strstr(char *haystack, char *needle);
